version: "3.9"

services:
  Client1:
    image: "ubuntu-ping"
    tty: true
    networks:
      - net1
    cap_add:
      - NET_ADMIN
    
  Client2:
    image: "ubuntu-ping"
    tty: true
    networks:
      - net2
    cap_add:
      - NET_ADMIN
    
  Transfer1:
    image: "ubuntu-ping"
    tty: true
    networks:
      - net1
      - transfer1
    cap_add:
      - NET_ADMIN
    
  Transfer2:
    image: "ubuntu-ping"
    tty: true
    networks:
      - net2
      - transfer1    
    cap_add:
      - NET_ADMIN
    
networks:
  net1:
    driver: bridge
  
  net2:
    driver: bridge
  
  transfer1:
    driver: bridge
