version: "3.9"

services:
  Client1:
    image: "ubuntu-ping"
    tty: true
    networks:
      net1:
        ipv4_address: 172.27.0.2
    cap_add:
      - NET_ADMIN
    
  Client2:
    image: "ubuntu-ping"
    tty: true
    networks:
      net2:
        ipv4_address: 172.26.0.2
    cap_add:
      - NET_ADMIN
    
  Transfer1:
    image: "ubuntu-ping"
    tty: true
    networks:
      net1:
        ipv4_address: 172.27.0.3
      transfernet1:
        ipv4_address: 172.25.0.3
    cap_add:
      - NET_ADMIN
    
  Transfer2:
    image: "ubuntu-ping"
    tty: true
    networks:
      net2:
        ipv4_address: 172.26.0.3
      transfernet1:
        ipv4_address: 172.25.0.2 
    cap_add:
      - NET_ADMIN
    
networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
  
  net2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1
  
  transfernet1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
